# This is a basic workflow to help you get started with Actions
 
name: Base-Workflow
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  #push:
    #branches:
      #- release
      #- 'migrations/**'
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
       CherryPick:
         description: 'CherryPick Scripts to Deploy'     
         required: true
         default: '0'
 
env:
 
  # Enable this for additional debug logging
  ACTIONS_RUNNER_DEBUG: true 
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Deploy Build
    # The type of runner that the job will run on
    runs-on: self-hosted
    environment: 'build' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configured 
    env:
      stage: 'Build'
      
      # Environment Secrets - In Real Ensure all of the below have been created as an Environment Secret (Projects Settings > Secrets > Actions section, specially related to the environment in question) #
      databaseName: "HUXSNOWFLAKE_BUILD"
      JDBC: "jdbc:snowflake://rv88946.west-europe.azure.snowflakecomputing.com/?db=HUXSNOWFLAKE_PROD&warehouse=COMPUTE_WH&jdbc_query_result_format=json" 
      displayName: 'Build'
      executeBuild: true
      publishArtifacts: true
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs the Flyway Clean command against the Build database
      - name: Clean Build DB
        if: env.executeBuild == 'true'
        run: |
          flyway -baselineOnMigrate="true" -user="HUXLEYKENDELL" -password="YogiBearRed99" -licenseKey="FL017D0549464A6CC40229E069E825513B15D4F0D2645DAAEE89CDA0786C3A668A1875ABEEBE7841FC3B4F8E0881FA90B3B0C3B28E5263CF9A75CF7611A32445A9D03AC2C73A851F5177A1FD90CE0BC28254FEB2E77CBB131986CA3FCDE9B46F95F0D63FAAAC892B55A1C1C0AC204AA8A7C4BA0370D67FD55BDBBA5334B91039A63F3B91A700BCC4F569EB739C77774D964AC440A8E152B6FC21D6FA50EC7F9BCCBD1E09ECFDED951CA6ABF7FE7AA3087E11451712803C47D919A8770CD98FA23E2482D90823C9B4C8F6DC8A3533342F2287152011FBCF7D0351493D42DC6256B766B470FCEF4F74197780B292390731055B346AA7A11D1DF72B6190FB41F20D18B0" -configFiles="C:\WorkingFolders\FWD\HuxS\flyway.toml" -locations="filesystem:C:\WorkingFolders\FWD\HuxS\migrations" info clean info -url="jdbc:snowflake://rv88946.west-europe.azure.snowflakecomputing.com/?db=HUXSNOWFLAKE_PROD&warehouse=COMPUTE_WH&jdbc_query_result_format=json" -cleanDisabled='false' -X
        
      # Runs the Flyway Migrate command against the Build database
      - name: Migrate Build DB
        if: env.executeBuild == 'true'
        run: |
          flyway -baselineOnMigrate="true" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" info migrate info -url="${{ env.JDBC }}" -cleanDisabled='false' -reportFilename="Reports\ValidateVScripts"
          

  prod:
    name: Deploy Production
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: Build
    environment: 'prod' #Ensure this environment name is setup in the projects Settings>Environment area. Ensuring any reviewers are also configured 
    if: ${{ true }} #Set this variable to false to temporarily disable the job
    env:
      stage: 'Prod'
      databaseName: "HUXSNOWFLAKE_PROD"
      JDBC: "jdbc:snowflake://rv88946.west-europe.azure.snowflakecomputing.com/?db=HUXSNOWFLAKE_PROD&jdbc_query_result_format=json" 
      pauseForCodeReview: true
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      # Runs the Flyway Migrate against the Production database
      - name: Migrate Build DB
        if: ${{ true }}
        run: |
          flyway -user="${{ env.userName }}" -password="${{ env.password }}" -baselineOnMigrate="true" -licenseKey="${{ env.FLYWAY_LICENSE_KEY }}" -configFiles="${{ GITHUB.WORKSPACE }}\flyway.toml" -locations="filesystem:${{ GITHUB.WORKSPACE }}\migrations" info migrate info -url="${{ env.JDBC }}" -cleanDisabled='false' -target='${{ github.event.inputs.CherryPick }}'
